"""initial schema

Revision ID: 9387aad1419f
Revises: 
Create Date: 2026-09-16 16:37:17.717625
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sentiment_mode', sa.String(length=16), nullable=False),
    sa.Column('llm_contaminated', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_delivery_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('notification_id', sa.String(length=36), nullable=True),
    sa.Column('to_address', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=320), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=True)
    op.create_table('job_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_runs_name_started', 'job_runs', ['job_name', 'started_at'], unique=False)
    op.create_table('llm_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_usage_created', 'llm_usage', ['created_at'], unique=False)
    op.create_table('market_prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', 'ts', name='uq_market_prices_sym_int_ts')
    )
    op.create_index('ix_market_prices_symbol_ts', 'market_prices', ['symbol', 'ts'], unique=False)
    op.create_table('raw_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('process_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key', 'external_id', name='uq_raw_events_source_external')
    )
    op.create_index(op.f('ix_raw_events_content_hash'), 'raw_events', ['content_hash'], unique=False)
    op.create_index('ix_raw_events_ingested', 'raw_events', ['ingestion_timestamp'], unique=False)
    op.create_index(op.f('ix_raw_events_processed'), 'raw_events', ['processed'], unique=False)
    op.create_index(op.f('ix_raw_events_source_key'), 'raw_events', ['source_key'], unique=False)
    op.create_table('source_health',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('items_last_poll', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_health_source_key'), 'source_health', ['source_key'], unique=True)
    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('poll_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_key'), 'sources', ['key'], unique=True)
    op.create_table('tickers',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_class', sa.String(length=24), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('sector_etf', sa.String(length=16), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('tickers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('event_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bullish_threshold', sa.Float(), nullable=True),
    sa.Column('bearish_threshold', sa.Float(), nullable=True),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('min_sample_size', sa.Integer(), nullable=False),
    sa.Column('include_low_confidence_tickers', sa.Boolean(), nullable=False),
    sa.Column('repeat_alerts', sa.Boolean(), nullable=False),
    sa.Column('max_per_hour', sa.Integer(), nullable=False),
    sa.Column('grouped_delivery', sa.Boolean(), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_rules_user', 'alert_rules', ['user_id', 'enabled'], unique=False)
    op.create_table('entity_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('ambiguous', sa.Boolean(), nullable=False),
    sa.Column('user_corrected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', 'ticker', name='uq_entity_alias_ticker')
    )
    op.create_index('ix_entity_aliases_alias', 'entity_aliases', ['alias'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('raw_event_id', sa.String(length=36), nullable=True),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=160), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('relevance_reason', sa.Text(), nullable=True),
    sa.Column('relevant', sa.Boolean(), nullable=False),
    sa.Column('analysis_status', sa.String(length=16), nullable=False),
    sa.Column('analysis_attempts', sa.Integer(), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=32), nullable=False),
    sa.Column('is_historical', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', name='uq_events_content_hash')
    )
    op.create_index(op.f('ix_events_analysis_status'), 'events', ['analysis_status'], unique=False)
    op.create_index(op.f('ix_events_is_historical'), 'events', ['is_historical'], unique=False)
    op.create_index(op.f('ix_events_relevant'), 'events', ['relevant'], unique=False)
    op.create_index(op.f('ix_events_source_key'), 'events', ['source_key'], unique=False)
    op.create_index('ix_events_source_ts', 'events', ['source_timestamp'], unique=False)
    op.create_index('ix_events_type', 'events', ['event_type'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.Integer(), nullable=True),
    sa.Column('quiet_hours_end', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('min_sample_size', sa.Integer(), nullable=False),
    sa.Column('max_per_hour', sa.Integer(), nullable=False),
    sa.Column('digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('digest_hour_local', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_notif_pref_user')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', name='uq_push_endpoint')
    )
    op.create_table('signal_state',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('armed', sa.Boolean(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('last_score', sa.Float(), nullable=True),
    sa.Column('last_crossed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', 'direction', name='uq_signal_state')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_watchlist_user_name')
    )
    op.create_table('claude_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=48), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('market_impact', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('time_horizon', sa.String(length=16), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', name='uq_claude_analyses_content_hash')
    )
    op.create_index(op.f('ix_claude_analyses_content_hash'), 'claude_analyses', ['content_hash'], unique=False)
    op.create_index(op.f('ix_claude_analyses_event_id'), 'claude_analyses', ['event_id'], unique=False)
    op.create_table('event_embeddings',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=96), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('event_tickers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('matched_alias', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('user_corrected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'ticker', name='uq_event_ticker')
    )
    op.create_index(op.f('ix_event_tickers_event_id'), 'event_tickers', ['event_id'], unique=False)
    op.create_index('ix_event_tickers_ticker', 'event_tickers', ['ticker'], unique=False)
    op.create_table('historical_event_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('matched_event_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('match_basis', sa.String(length=32), nullable=False),
    sa.Column('returns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'ticker', 'matched_event_id', name='uq_hist_match')
    )
    op.create_index('ix_hist_match_event', 'historical_event_matches', ['event_id', 'ticker'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('notification_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_notifications_idempotency')
    )
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index('ix_notifications_unread', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('horizon', sa.String(length=8), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('sample_flag', sa.String(length=16), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('historical_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uncertainties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'ticker', name='uq_signal_event_ticker')
    )
    op.create_index(op.f('ix_signals_event_id'), 'signals', ['event_id'], unique=False)
    op.create_index('ix_signals_ticker_created', 'signals', ['ticker', 'created_at'], unique=False)
    op.create_table('watchlist_tickers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('watchlist_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'ticker', name='uq_watchlist_ticker')
    )
    op.create_index(op.f('ix_watchlist_tickers_watchlist_id'), 'watchlist_tickers', ['watchlist_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('provider_response', sa.Text(), nullable=True),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deliveries_notification', 'notification_deliveries', ['notification_id'], unique=False)
    op.create_index('ix_deliveries_status', 'notification_deliveries', ['status'], unique=False)
    # ### end Alembic commands ###

    # Full-text search index backing GET /api/search. Expression must match the
    # one in api/routes_feed.py exactly or the index will not be used.
    # coalesce/|| rather than concat_ws: concat_ws is only STABLE, and Postgres
    # rejects non-IMMUTABLE functions in an index expression.
    op.execute(
        """
        CREATE INDEX ix_events_fts ON events
        USING GIN (to_tsvector('english',
            coalesce(title, '') || ' ' || coalesce(text, '') || ' ' || coalesce(source_key, '')
        ))
        """
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_events_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deliveries_status', table_name='notification_deliveries')
    op.drop_index('ix_deliveries_notification', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_watchlist_tickers_watchlist_id'), table_name='watchlist_tickers')
    op.drop_table('watchlist_tickers')
    op.drop_index('ix_signals_ticker_created', table_name='signals')
    op.drop_index(op.f('ix_signals_event_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index('ix_notifications_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_hist_match_event', table_name='historical_event_matches')
    op.drop_table('historical_event_matches')
    op.drop_index('ix_event_tickers_ticker', table_name='event_tickers')
    op.drop_index(op.f('ix_event_tickers_event_id'), table_name='event_tickers')
    op.drop_table('event_tickers')
    op.drop_table('event_embeddings')
    op.drop_index(op.f('ix_claude_analyses_event_id'), table_name='claude_analyses')
    op.drop_index(op.f('ix_claude_analyses_content_hash'), table_name='claude_analyses')
    op.drop_table('claude_analyses')
    op.drop_table('watchlists')
    op.drop_table('signal_state')
    op.drop_table('push_subscriptions')
    op.drop_table('notification_preferences')
    op.drop_index('ix_events_type', table_name='events')
    op.drop_index('ix_events_source_ts', table_name='events')
    op.drop_index(op.f('ix_events_source_key'), table_name='events')
    op.drop_index(op.f('ix_events_relevant'), table_name='events')
    op.drop_index(op.f('ix_events_is_historical'), table_name='events')
    op.drop_index(op.f('ix_events_analysis_status'), table_name='events')
    op.drop_table('events')
    op.drop_index('ix_entity_aliases_alias', table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index('ix_alert_rules_user', table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_table('users')
    op.drop_table('tickers')
    op.drop_index(op.f('ix_sources_key'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_source_health_source_key'), table_name='source_health')
    op.drop_table('source_health')
    op.drop_index(op.f('ix_raw_events_source_key'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_processed'), table_name='raw_events')
    op.drop_index('ix_raw_events_ingested', table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_content_hash'), table_name='raw_events')
    op.drop_table('raw_events')
    op.drop_index('ix_market_prices_symbol_ts', table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index('ix_llm_usage_created', table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index('ix_job_runs_name_started', table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_table('entities')
    op.drop_table('email_delivery_logs')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
